#!/usr/bin/python3
import sys


def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <file>")
        sys.exit(1)

    with open(sys.argv[1]) as f:
        for line in f:
            n = int(line.strip())
            for i in range(2, n):
                if n % i == 0 and is_prime(i) and is_prime(n // i):
                    print(f"{n}={n // i}*{i}")
                    break


if __name__ == "__main__":
    main()
